### PR TITLE
Improved timming system

### PR DESCRIPTION
**Pull request by raysan5**

### CODE REVIEW

**Comment by raysan5** [comment]
Reviewing raylib timming system I'm not sure now if this implementation is correct (about `baseTime` requirement), don't merge yet!

**Comment by victorfisac** [comment]
Hey @raysan5 ! I saw in raylib repo some changes in physac and I was going to update it when having some time... Thank you for the update! :D I will wait for you to merge it.

**Comment by raysan5** [comment]
HI @victorfisac, just reviewed timming system again, not it works ok.

**Comment by victorfisac** [comment]
@raysan5 thanks! :)

**Pull request merged**
